### ISSUE TITLE
Improve specificity of errors on legislation parsing

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#370] opened 2016-01-11 09:56 UTC
When `param.xml` is not valid, the traceback and the exception message is not as clear as it could be.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/cbenz/Dev/openfisca/openfisca-france/openfisca_france/tests/test_basics.py", line 8, in <module>
    from openfisca_france.tests import base
  File "/home/cbenz/Dev/openfisca/openfisca-france/openfisca_france/tests/base.py", line 29, in <module>
    tax_benefit_system = TaxBenefitSystem()
  File "/home/cbenz/Dev/openfisca/openfisca-core/openfisca_core/taxbenefitsystems.py", line 125, in __init__
    legislation_json = self.get_legislation_json(with_source_file_infos = False)
  File "/home/cbenz/Dev/openfisca/openfisca-core/openfisca_core/taxbenefitsystems.py", line 136, in get_legislation_json
    legislation_json = conv.check(xml_legislation_info_list_to_json)(self.legislation_xml_info_list, state = state)
  File "/home/cbenz/.local/lib/python2.7/site-packages/biryani/baseconv.py", line 2728, in check_converter
    raise ValueError(u'{0} for: {1}'.format(error, value).encode('utf-8'))
ValueError: OrderedDict([('NODE', {10: OrderedDict([('NODE', {16: OrderedDict([('NODE', {1: OrderedDict([('CODE', {2: OrderedDict([('VALUE', {12: {'deb': u'Dates of values overlap'}})])})])})])})])})]) for: OrderedDict([('code', 'root'), ('NODE', [OrderedDict([('code', 'al'), ('description', 'Allocations logement'), ('NODE', [OrderedDict([('code', 'R1'), ('description', 'R1 (% du RMI)'), ('CODE', [OrderedDict([('code', 'taux1'), ('description', 'Taux pour 1 adulte'), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2015-01-01'), ('valeur', '0.88')]), OrderedDict([('deb', u'2002-01-01'), ('fin', u'2014-12-31'), ('valeur', '0.88')])])]), OrderedDict([('code', 'taux2'), ('description', 'Taux pour 2 adultes'), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2015-01-01'), ('valeur', '1.26')]), OrderedDict([('deb', u'2002-01-01'), ('fin', u'2014-12-31'), ('valeur', '1.26')])])]), OrderedDict([('code', 'taux3'), ('description', 'Taux pour 1 enfant'), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2015-01-01'), ('valeur', '1.503')]), OrderedDict([('deb', u'2002-01-01'), ('fin', u'2014-12-31'), ('valeur', '1.503')])])]), OrderedDict([('code', 'taux4'), ('description', 'Taux pour 2 enfants'), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2015-01-01'), ('valeur', '1.803')]), OrderedDict([('deb', u'2002-01-01'), ('fin', u'2014-12-31'), ('valeur', '1.803')])])]), OrderedDict([('code', 'taux5'), ('description', u'Taux par enfants suppl\xe9mentaires'), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2015-01-01'), ('valeur', '0.4')]), OrderedDict([('deb', u'2002-01-01'), ('fin', u'2014-12-31'), ('valeur', '0.4')])])])])]), OrderedDict([('code', 'R2'), ('description', 'R2 (% de la BMAF)'), ('CODE', [OrderedDict([('code', 'taux4'), ('description', 'Taux pour 2 enfants'), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2015-01-01'), ('valeur', '0.32')]), OrderedDict([('deb', u'2002-01-01'), ('fin', u'2014-12-31'), ('valeur', '0.32')])])]), OrderedDict([('code', 'taux5'), ('description', u'Taux par enfants suppl\xe9
[...]
```

The error is structured with indexes corresponding to the node children, but we'd like to see the name of the parameter at least, or an XML snippet showing the error in a more understandable context.

**Comment by MattiSG** [comment] 2017-04-20 10:25
Duplicate of #474.

**Closed** 2017-04-20 17:18 UTC
Labels: developer-experience, enhancement
