### ISSUE TITLE
Handle table parameters

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#473] opened 2017-03-16 15:16 UTC
As a legislation writer,
I can easily put [this kind of parameters](https://www.legifrance.gouv.fr/eli/arrete/2016/3/22/MENE1606432A/jo) in my tax and benefit systems.
Because It's a nightmare in the current XML

**Comment by Morendil** [comment] 2018-11-16 10:40
Duplicate of https://github.com/openfisca/openfisca-france/issues/1167

**Closed by Morendil** 2018-11-16 10:40 UTC
Labels: flow:qualified-issues, note:developer-experience
