### ISSUE TITLE
Enhance API version tracking

### ISSUE THREAD

**Issue by Anna-Livia** [openfisca/openfisca-core#637] opened 2018-04-10 13:14 UTC
As a developer, I want to know how many users are on the current API version Vs old ones so I can know how many versions I need to mantain

**Comment by MattiSG** [comment] 2018-05-18 03:39
Duplicate of https://github.com/openfisca/openfisca-core/issues/594, I believe. Feel free to reopen with more details if that's not the case 🙂

**Closed by MattiSG** 2018-05-18 03:39 UTC
