### ISSUE TITLE
Timeout on MBP mid-2009

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#504] opened 2017-05-11 12:38 UTC
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
```
➜  mes-aides-ui git:(fix_535) ✗ npm run openfisca

> sgmap-mes-aides-ui@1.0.0 openfisca /repos/mes-aides/mes-aides-ui
> gunicorn --workers 1 --paster openfisca/api_config.ini

[2017-05-11 14:25:24 +0200] [6139] [INFO] Starting gunicorn 19.7.1
[2017-05-11 14:25:24 +0200] [6139] [INFO] Listening at: http://0.0.0.0:2000 (6139)
[2017-05-11 14:25:24 +0200] [6139] [INFO] Using worker: sync
[2017-05-11 14:25:24 +0200] [6340] [INFO] Booting worker with pid: 6340
2017-05-11 14:25:37,457 DEBUG [openfisca_web_api.environment] Pre-fill tax and benefit system cache.
2017-05-11 14:25:39,873 DEBUG [openfisca_web_api.environment] Initialize reforms.
2017-05-11 14:25:39,874 DEBUG [openfisca_web_api.environment] Cache default decomposition.
2017-05-11 14:25:40,462 DEBUG [openfisca_web_api.environment] Initialize lib2to3-based input variables extractor.
2017-05-11 14:25:40,466 DEBUG [openfisca_web_api.environment] Cache legislation JSON with references to original XML.
[2017-05-11 14:25:54 +0200] [6139] [CRITICAL] WORKER TIMEOUT (pid:6340)
[2017-05-11 14:25:54 +0200] [6340] [INFO] Worker exiting (pid: 6340)
[2017-05-11 14:25:55 +0200] [6479] [INFO] Booting worker with pid: 6479
```

### Here is data (or links to it) that can help you reproduce this issue:

![capture d ecran 2017-05-11 a 14 28 52](https://cloud.githubusercontent.com/assets/1410356/25948985/31f37086-3656-11e7-8c5b-a1afc080913d.png)

### How I overcome this issue

I specify a long timeout in my gunicorn configuration (`timeout = 60000`).

## Context

I identify more as a:
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by MattiSG** [comment] 2017-05-18 08:58
Thanks for reporting this issue! I am glad that you found a workaround, and thank you very much for documenting it here for other users! I am wondering whether #505 could have improved the situation. If you get a chance to test with a version higher than 12.1.3, a report of changes (or not) would be very welcome :smiley:

**Comment by MattiSG** [comment] 2017-07-24 15:49
I think this is now a duplicate of the more detailed https://github.com/openfisca/openfisca-core/issues/535, and will close this issue as such.

If that's not the case, please feel free to reopen it! 🙂

**Closed by MattiSG** 2017-07-24 15:49 UTC
Labels: developer-experience, performance
