### ISSUE TITLE
Simplify period management

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#442] opened 2017-02-01 10:23 UTC
## Observations

Looking at `openfisca-france`, it seems that most of the variables have a natural period granularity. For instance, the `rsa` is defined for a month, while `irpp` defined for a year.

## Current situation

The way this natural period is set for a given formula is today complex and confusing. For instance : 
```py
class rsa(Variable):
    [...]

    def function(famille, period):
        period = period.this_month
        [...]
        return period, result

```
The current implementation allows a formula to return a result for a different period than the one it has been called for.

For instance, if I call `rsa` for `2015`, the first line`period = period.this_month` will change `period` to `2015-01`. This period will be returned with the result. It is then the openfisca middleware that will check that the returned period is the same than the required one. In our case, it will throw an error except if a certain option has been set for the calculation.

### Problems caused
- Returning the period with the result is not natural, and often forgotten.
- The first line, which defines the natural period of the formula, is really unclear.
- The first line is repeated in almost all formulas.

## Proposition
If each variable has a natural period, then a **declarative approach** seems more simple.

### Example
Our previous formula becomes : 
```py
class rsa(Variable):
    period = MONTH # keyword to be discussed
    [...]

    def function(famille, period):
        [...]
        return result

```

### Behaviour
- If I call a variable for a period that is **not its natural one**, **an error is raised** before entering the formula.
    - For instance if I call `rsa` for `2015`, or `irpp` for `2015-01`.
- If a formula has no natural period, we do not check anything (some variables are period agnostics, for instance inputs or basis input combinations)

**Comment by fpagnoux** [comment] 2017-02-01 10:24
@MattiSG @cbenz @benjello @michelbl : do you share the same analysis, and agree with the proposition ?

**Comment by fpagnoux** [comment] 2017-02-01 10:34
Some leads for the implem:
- [`formulas.compute`](https://github.com/openfisca/openfisca-core/blob/4.3.2/openfisca_core/formulas.py#L333) is probably where things should happen and [this block](https://github.com/openfisca/openfisca-core/blob/4.3.2/openfisca_core/formulas.py#L396) should will certainly be removed.

**Comment by benjello** [comment] 2017-02-01 10:38
I strongly agree with the proposition. 

I think we should also take into account what should be the next step which is using `options = [ADD]` when we wont the sum over natural periods of a variable.
IMHO, the `ADD` part should be on the `Variable` side. The variable should define how it is aggregated when called over a year, few months etc. Therefore, it is important that this very useful change won't preclude the long-term goal.

**Comment by fpagnoux** [comment] 2017-02-01 10:44
We came to the same conclusion with @michelbl. I don't think implementing this will conflict with this potential future feature, so let's keep it separated on work with this issue first :).

**Comment by benjello** [comment] 2017-02-01 11:20
@fpagnoux : I just wanted to make sure we are on line for the long-term goals. I accepted too many "improvements" that resulted in huge debt or regressions for my use cases.

**Comment by MattiSG** [comment] 2017-02-01 12:39
I'm neutral, and would support such a change. The proposed implementation clearly improves readability, but I haven't felt this pain recently enough to have a strong opinion.

If there is a very uneven distribution of “natural periods” (i.e. 80% are month, 15% year, 5% other), I would also be in favour of having a _default natural period_.

**Comment by michelbl** [comment] 2017-02-01 13:28
@MattiSG There are already lots of default values in the code of openfisca-core, some of them are hard to trace back, and I think this is the cause of unnecessary complexity. At least if we add implicit rules we should be rigorous with documentation.

**Comment by fpagnoux** [comment] 2017-02-01 13:35
Among the formulas who have a natural period today :
- year : `60%`
- month : `40%`

**Comment by benjello** [comment] 2017-02-01 13:37
When period matters, explicit is definitively better than implicit.

**Comment by cbenz** [comment] 2017-02-01 14:44
I support this change.

I agree the long-term goals @benjello talked about, in particular the fact that the variable is responsible about how to combine its value with other values. While this issue is not about that, it's a first step towards.

I am willing to assist @michelbl for the implementation and for transforming the code of the exiting variables in `openfisca-france`. If manual search/replace is too weak, there is the [redbaron](https://github.com/PyCQA/redbaron) refactoring library which fits the need.

**Comment by cbenz** [comment] 2017-02-01 18:29
This is a draft.

Following a discussion with @michelbl:

- API example:
  ```python
  class irpp(Variable):
      period_unit = MONTH
  ```
  `period_unit` may be called `periodicity` or `computes_on`
  It would be a required attribute
- `period_unit` is an enum of `{MONTH, YEAR, NO_UNIT}` (`NO_UNIT` may be called `PERMANENT`)
- `new_filled_column` must check its value
- this applies to input variables too
- now a formula can modify its input period in order to call another variable, but the output value must always correspond to the input period
  - as a consequence it is forbidden to use sliding years or months (see https://legislation.openfisca.fr/variables/decote)
- is it possible to call a variable on both periods (month and year)?
- is it possible to compute a formula on instants (and not periods)?
  Is there any formula that uses `period = period.start` or such?
- for the formulas written after the modification involved by this issue, it will be the responsibility of its author to ensure the output result corresponds to the input period. The Core will not be able to check it by itself anymore.  

Implementation related:
- use a cache dict by period unit
- the cache stores values by period as the caller gives it, not by output period anymore
- there is already an attribute [`is_permanent`](https://github.com/openfisca/openfisca-france/blob/04355b1b570e9df95204d2edc5f890e546116149/openfisca_france/model/caracteristiques_socio_demographiques/demographie.py#L6-L10): we remove it
- in a first stage we can keep the returned `period, result` tuple, to check that the output period equals the input period for all the existing variables
  - then we'll replace it by `return result`

List of special variables:
- `date_de_naissance`
- `nb_enfants_a_charge`
- to be continued

Remind to:
- update the documentation before shipping

**Comment by MattiSG** [comment] 2017-02-01 18:33
So as seen IRL @michelbl takes this issue, and it's now part of the sprint! 🕺

**Comment by benjello** [comment] 2017-02-01 18:41
There might be some confusion here:
  - period_unit:
    - NO_UNIT means I can compute the value for any period you asked for
    - PERMANENT means I always return the same value independently of the period
  - We may want formula that can be computed monthly and yearly
  - No computation at instant right now

**Comment by fpagnoux** [comment] 2017-02-01 21:22
>now a formula can modify its input period in order to call another variable, but the output value must always correspond to the input period

Let's keep the model simple: we don't need differentiate the input and the output period. They should be the same by design. A formula never modifies "its input period". It can use other periods for sub-calculations, for instance `period.that_year`, but `period` stay the same. 

The convention is thus clear and natural : when I call a formula for `2015`, I know the result I get is for `2015`.

>use a cache dict by period unit

Not sure what this means.

>the cache stores values by period as the caller gives it, not by output period anymore
They are now the same :)

>in a first stage we can keep the returned period, result tuple, to check that the output period equals the input period for all the existing variables

I don't understand. A variable doesn't _have_ an input period, it is called _with_ one, so I don't know what there is to check.

Let's try to find some time to talk about it IRL tomorrow ;)

**Comment by michelbl** [comment] 2017-02-03 14:45
> Let's keep the model simple: we don't need differentiate the input and the output period. They should be the same by design. A formula never modifies "its input period". It can use other periods for sub-calculations, for instance period.that_year, but period stay the same.
> The convention is thus clear and natural : when I call a formula for 2015, I know the result I get is for 2015.

We all agree on that.

> use a cache dict by period unit
> Not sure what this means.

If a formula is montly and the computation is done on a whole year, 12 computations are done and 12 results are cached.

> They are now the same :)

Yes indeed.

> I don't understand. A variable doesn't have an input period, it is called with one, so I don't know what there is to check.

We can keep the returned period for debugging purposes, and raise an exception if the returned period is different from the argument (the check can be done in exec_function). When the tests pass, we are confident there are no more period manipulations inside formulas. This is also a way to spot tricky formulas.

**Comment by michelbl** [comment] 2017-02-03 15:05
> There might be some confusion here:
> 
> period_unit:
> NO_UNIT means I can compute the value for any period you asked for
> PERMANENT means I always return the same value independently of the period
> We may want formula that can be computed monthly and yearly
> No computation at instant right now

I think that a *formula* is always applied on a month *or* a year. A *variable* is computed using a formula or using cached input data. A variable may be called on any period (1 year, n years, 1 month, n months) or can be constant (then it is an input variable with no formula). In the end there are 3 cases concerning period granularity :
* a variable is computed using a monthly formula or a monthly cache
* a variable is computed using a yearly formula or a yearly cache
* a variable is constant (implies there is no formula and this is an input variable)

The way a variable uses its formula is the matter of another PR.

@benjello Do you agree on that ?

**Comment by benjello** [comment] 2017-02-03 16:12
I agree @michelbl that is the actual state. I do not know if other use-cases case can arise.

**Comment by fpagnoux** [comment] 2017-02-04 21:48
Whether the period unit should be an attribute of the `formula` or of the `variable` is a very good, tricky, and interesting question 👍 . Let's try to think this through and to get a consensus.

I've read that "a variable may be called on any period", but this statement is a design choice and needs to be discussed. Does a `rsa` exist for `2013-2014` ? Its sum exist, its average too, but the `rsa` itself ?

@benjello, among the variables you know, would you say that **the formula to compute them** have a natural period unit, or that the **variable themselves** have one. For the one I know in the social prestations world, it is more the variable which is well defined for a given period.

The concrete behaviour question behind this is : should we control the period units of users input ? When I set the input of my simulation, can I declare a `rsa` for `2015`, or should I get an error if I try ? Can I declare an `irpp` for `2015-04` ?

**Comment by benjello** [comment] 2017-02-04 22:18
There are two response depending on the nature of the variable:
 - an intensive variable say `activite` can virtually change anytime and therefore there is no downward period unit limit (although a day would be a good backstop)
 - an extensive variable does usually have a time quanta:   `rsa` and `af` are _per_ month other but may not like `salaire_imposable` that could be for a day (you work one day) but it is coded on a monthly basis by choice (and I think is a good thing).

And yes we should definitively control for the input periods. And we should allow, at least as an option, other checks on type, positiveness, value range etc to increase robustness.

**Comment by fpagnoux** [comment] 2017-02-14 14:49
Agreed with @cbenz @michelbl, @benjello on the phone and me:

- Introduce a `period_unit` attribute on each `Variable`. This attribute is mandatory. The possible values are `MONTH`, `YEAR`, `PERMANENT`, and possibly `ANY` or others if we need other behaviours.

- Ensure that in the cache, the value are always stored for a period that matches the period unit of the variable.

- Ensure that variables are always calculated for a period that matches its period unit.

**Comment by michelbl** [comment] 2017-02-16 13:23
> Introduce a period_unit attribute on each Variable. This attribute is mandatory. The possible values are MONTH, YEAR, PERMANENT, and possibly ANY or others if we need other behaviours.

`period_unit` was renamed in `period_behavior` to have a unique name

> Ensure that in the cache, the value are always stored for a period that matches the period unit of the variable.

OK

> Ensure that variables are always calculated for a period that matches its period unit.

Yet to be done.

**Comment by MattiSG** [comment] 2017-03-07 07:58
Nope, this is not done, the documentation is still not merged: https://github.com/openfisca/openfisca-gitbook/pull/32

**Comment by fpagnoux** [comment] 2017-03-07 08:29
This is _exactly_ why I don't like using `Fixes #n`

**Comment by MattiSG** [comment] 2017-03-07 08:35
I think I'm responsible for having written `Fixes`. At that time, the documentation PR did not exist yet.

**Closed** 2017-03-07 12:56 UTC
